name: sam_server_web_client
description: A sample web application
dependencies:
  browser: any
  cs_elements:
    path: /Users/ovangle/Programming/sam_server3_workspace/cs_elements
  polymer: any
  quiver: any
  core_elements: '>=0.5.0'
transformers:
- polymer:
    entry_points:
    - web/index.html
    - web/asset.html
    - web/auth/login.html
    - web/auth/register.html
    - example/asset_details.html
    - example/asset_list.html
    - example/main_context_example.html
    - example/strength_meter.html
